In [1]:
import numpy as np


In [2]:
l1=[1,2,3,4,5]
print(l1)
np.array(l1)

[1, 2, 3, 4, 5]


array([1, 2, 3, 4, 5])

In [17]:
m1=[[1,2,3],[4,5,6],[7,8,9]]
print(m1)
np.array(m1)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
m2=np.arange(1,18,2)
print(m2.reshape(3,3))

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


In [37]:
arr=np.random.uniform(0,10,10)
arr

array([8.61391212, 0.57146554, 3.95014655, 4.78433339, 1.39377734,
       7.95459644, 0.4210381 , 2.36259598, 6.32019621, 0.66649656])

In [44]:
narr=np.array([1,2,3,4,5])
new=narr.reshape(5,1)
new

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [45]:
new.shape

(5, 1)

In [48]:
arr2=np.array([1,2,3,4,5,6,7,8,9,0])
arr2[2],arr2[3],arr2[8]

(3, 4, 9)

In [75]:
arr2=np.array([1,2,3,4,5,6,7,8,9,0])
arr2[0::2]

array([1, 3, 5, 7, 9])

In [77]:
arr3=np.array([0,0,0,0,0,0,0,92,91,100])
print(arr2+arr3)

[  1   2   3   4   5   6   7 100 100 100]


In [111]:
f=np.random.rand(25).reshape(5,5)
print(f)
print('\nThe 3x3 matrix is:\n',f[1:4,1:4])

[[0.59869153 0.34050631 0.52775288 0.7456834  0.67083289]
 [0.45763184 0.46920262 0.99170097 0.80395791 0.5590507 ]
 [0.00622636 0.4812892  0.62806285 0.93353868 0.69940509]
 [0.37028358 0.27740919 0.92012599 0.06908736 0.10846855]
 [0.82391997 0.92401791 0.94241076 0.57596226 0.77765803]]

The 3x3 matrix is:
 [[0.46920262 0.99170097 0.80395791]
 [0.4812892  0.62806285 0.93353868]
 [0.27740919 0.92012599 0.06908736]]
